INSERT INTO PUBLIC.CATEGORY (ID, NOME) VALUES (1, 'Iluminação');
INSERT INTO PUBLIC.CATEGORY (ID, NOME) VALUES (2, 'buraco');
INSERT INTO PUBLIC.CATEGORY (ID, NOME) VALUES (3, 'lixo');
INSERT INTO PUBLIC.CATEGORY (ID, NOME) VALUES (4, 'placa de sinalização');